version: '3.8'
services:
  load_balancer:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - app1
      - app2
      - app3
      - app4
  app1:
    image: inblack67/app:latest
    environment:
      - PORT=5000
  app2:
    image: inblack67/app:latest
    environment:
      - PORT=5001
  app3:
    image: inblack67/app:latest
    environment:
      - PORT=5002
  app4:
    image: inblack67/app:latest
    environment:
      - PORT=5003
